version: '3'

vars:
  PROJECT_NAME: react-analytics-ui

tasks:
  install:
    desc: Install dependencies
    cmds:
      - npm install

  build:
    desc: Build the library for production
    cmds:
      - npm run build

  dev:
    desc: Start Storybook development server
    cmds:
      - npm run storybook

  build-storybook:
    desc: Build Storybook for deployment
    cmds:
      - npm run build-storybook

  lint:
    desc: Run ESLint
    cmds:
      - npm run lint

  lint-fix:
    desc: Run ESLint with auto-fix
    cmds:
      - npm run lint -- --fix

  type-check:
    desc: Run TypeScript type checking
    cmds:
      - npm run type-check

  test:
    desc: Run tests
    cmds:
      - npm test

  clean:
    desc: Remove build artifacts and node_modules
    cmds:
      - rm -rf dist storybook-static node_modules

  generate-ai-docs:
    desc: Generate AI-consumable documentation for component library
    cmds:
      - node scripts/generate-ai-docs.js

  validate:
    desc: Run all validation checks (lint, type-check, build)
    cmds:
      - task: lint
      - task: type-check
      - task: build

  format:
    desc: Format code (add prettier if needed)
    cmds:
      - echo "Add prettier configuration for code formatting"

  prepublish:
    desc: Prepare package for publishing
    cmds:
      - task: clean
      - task: install
      - task: validate
      - task: test

  publish:
    desc: Publish package to npm
    cmds:
      - task: prepublish
      - npm publish

  default:
    desc: Display available tasks
    cmds:
      - task --list
