FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --production

# Copy subscriber script
COPY subscriber.js ./

# Run subscriber
CMD ["node", "subscriber.js"]
